### ISSUE TITLE
feat : Connect api with login logout frontend

### ISSUE THREAD

**Issue by vinhyenvodoi98** [vinhyenvodoi98/workflow_management_php_laravel#11]
Connect jwt api to frontend
first migrate database with commad in workflow/php container 
```sh
 php artisan migrate --force
```

Now we have : 
## POST http://localhost:8181/api/signup
![image](https://user-images.githubusercontent.com/33363513/66935040-a01b0800-f065-11e9-83a5-56b5800be0a5.png)

## POST http://localhost:8181/api/login
![image](https://user-images.githubusercontent.com/33363513/66935132-c2ad2100-f065-11e9-9c08-81e7b414530d.png)

## GET http://localhost:8181/api/auth
![image](https://user-images.githubusercontent.com/33363513/66935175-d789b480-f065-11e9-91c2-5c2b5a4b706a.png)

## GET http://localhost:8181/api/token/refresh
![image](https://user-images.githubusercontent.com/33363513/66935333-07d15300-f066-11e9-9a44-21dab35d06d1.png)

## POST http://localhost:8181/api/logout
![image](https://user-images.githubusercontent.com/33363513/66935397-1ae42300-f066-11e9-9087-3fd295a8e50c.png)

# **TODO**

- [x] connect to login page
- [x] connect to register page
- [x] check token for auto login (store jwt in local storeage)
- [x] need logout
